[package]
name = "rust-kata-skeletons"
version = "0.1.0"
authors = ["Thomas Barusseau <thomas.barusseau@protonmail.com>"]
edition = "2018"
default-run = "rust-kata-skeletons"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
